"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import PosHeader from "@/components/pos/PosHeader";
import { supabase } from "@/lib/supabase";

type Item = { id: string; name: string; unit: string; shop_stock: number; store_stock: number; low_stock_threshold: number; notes: string | null; is_active: boolean };
type StockForm = { name: string; unit: string; shop_stock: string; store_stock: string; low_stock_threshold: string; notes: string };
const blank = (): StockForm => ({ name: "", unit: "packets", shop_stock: "0", store_stock: "0", low_stock_threshold: "1", notes: "" });
const count = (value: number) => Number(value).toLocaleString(undefined, { maximumFractionDigits: 2 });

export default function StockPage() {
  const [items, setItems] = useState<Item[]>([]);
  const [form, setForm] = useState<StockForm>(blank);
  const [editing, setEditing] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  const [notice, setNotice] = useState("");
  const [search, setSearch] = useState("");
  const load = useCallback(async () => { setLoading(true); const { data, error } = await supabase.from("inventory_items").select("*").eq("is_active", true).order("name"); setItems((data as Item[]) ?? []); setNotice(error ? `Stock load nahi ho saka: ${error.message}` : ""); setLoading(false); }, []);
  useEffect(() => { void load(); }, [load]);
  const alerts = useMemo(() => items.filter(x => Number(x.shop_stock) <= Number(x.low_stock_threshold)), [items]);
  const visible = useMemo(() => items.filter(x => x.name.toLowerCase().includes(search.toLowerCase())), [items, search]);
  const shopTotal = useMemo(() => items.reduce((sum, x) => sum + Number(x.shop_stock), 0), [items]);
  const storeTotal = useMemo(() => items.reduce((sum, x) => sum + Number(x.store_stock), 0), [items]);
  const set = <K extends keyof StockForm>(key: K, value: StockForm[K]) => setForm(old => ({ ...old, [key]: value }));
  async function save(event: FormEvent) {
    event.preventDefault();
    const shop_stock = Number(form.shop_stock), store_stock = Number(form.store_stock), low_stock_threshold = Number(form.low_stock_threshold);
    if (!form.name.trim() || [shop_stock, store_stock, low_stock_threshold].some(x => !Number.isFinite(x) || x < 0)) { setNotice("Item name aur valid stock quantity enter karein."); return; }
    const record = { name: form.name.trim(), unit: form.unit.trim() || "packets", shop_stock, store_stock, low_stock_threshold, notes: form.notes.trim() || null };
    const { error } = editing ? await supabase.from("inventory_items").update({ ...record, updated_at: new Date().toISOString() }).eq("id", editing) : await supabase.from("inventory_items").insert(record);
    if (error) { setNotice(`Save nahi ho saka: ${error.message}`); return; }
    setNotice(editing ? "Stock item update ho gaya." : "Stock item add ho gaya."); setEditing(null); setForm(blank()); void load();
  }
  function edit(item: Item) { setEditing(item.id); setForm({ name:item.name, unit:item.unit, shop_stock:String(item.shop_stock), store_stock:String(item.store_stock), low_stock_threshold:String(item.low_stock_threshold), notes:item.notes ?? "" }); window.scrollTo({ top: 0, behavior: "smooth" }); }
  async function transfer(item: Item) {
    const answer = window.prompt(`Store se shop mein kitne ${item.unit} transfer karne hain?\nAvailable in store: ${count(Number(item.store_stock))}`, "1");
    if (answer === null) return;
    const quantity = Number(answer);
    if (!Number.isFinite(quantity) || quantity <= 0 || quantity > Number(item.store_stock)) { setNotice("Transfer quantity valid nahi hai ya store stock se zyada hai."); return; }
    const { error } = await supabase.from("inventory_items").update({ shop_stock: Number(item.shop_stock) + quantity, store_stock: Number(item.store_stock) - quantity, updated_at: new Date().toISOString() }).eq("id", item.id);
    setNotice(error ? `Transfer nahi ho saka: ${error.message}` : `${count(quantity)} ${item.unit} shop mein transfer ho gaye.`); if (!error) void load();
  }
  async function archive(item: Item) { if (!window.confirm(`“${item.name}” ko stock list se remove karein?`)) return; const { error } = await supabase.from("inventory_items").update({ is_active:false, updated_at:new Date().toISOString() }).eq("id", item.id); setNotice(error ? error.message : "Item remove ho gaya."); if (!error) void load(); }
  return <><div className="no-print"><PosHeader todayTotal={0}/></div><main className="mx-auto max-w-7xl px-4 py-6 sm:px-6">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-body text-xs font-extrabold uppercase tracking-[.18em] text-mustard">Inventory control</p><h1 className="font-display text-3xl text-[#f5f4fb]">Stock Manager</h1></div><div className="rounded-xl border border-[#f5f4fb]/10 bg-[#14111a] px-4 py-3 text-right"><p className="font-body text-[10px] font-extrabold uppercase text-[#f5f4fb]/45">Low shop stock alerts</p><p className={`font-display text-2xl ${alerts.length ? "text-chili" : "text-leaf"}`}>{alerts.length}</p></div></div>
    {alerts.length > 0 && <section className="mt-5 rounded-xl border border-chili/40 bg-chili/10 p-4"><p className="font-body text-sm font-extrabold text-chili">⚠ Stock alert — {alerts.length} item{alerts.length > 1 ? "s" : ""} is at the last packet / low level.</p><div className="mt-2 flex flex-wrap gap-2">{alerts.map(x => <span key={x.id} className="rounded-full border border-chili/30 bg-[#14111a] px-3 py-1 font-body text-xs font-bold text-[#f5f4fb]">{x.name}: {count(Number(x.shop_stock))} {x.unit}{Number(x.store_stock) > 0 ? ` · Store has ${count(Number(x.store_stock))}` : " · Store empty"}</span>)}</div></section>}
    <section className="mt-6 grid gap-5 lg:grid-cols-[1fr_330px]"><form onSubmit={save} className="rounded-2xl border border-[#f5f4fb]/10 bg-[#14111a] p-5"><div className="flex justify-between"><h2 className="font-display text-xl text-[#f5f4fb]">{editing ? "Edit stock item" : "Add stock item"}</h2>{editing && <button type="button" onClick={() => {setEditing(null);setForm(blank());}} className="font-body text-xs font-bold text-mustard">Cancel</button>}</div><div className="mt-4 grid gap-3 sm:grid-cols-2"><Field label="Item name *" value={form.name} onChange={v=>set("name",v)} placeholder="e.g. Zinger fillet" wide/><Field label="Unit" value={form.unit} onChange={v=>set("unit",v)} placeholder="packets, kg, bottles"/><Field label="Low-stock alert at *" type="number" value={form.low_stock_threshold} onChange={v=>set("low_stock_threshold",v)} placeholder="1"/><Field label="Stock in shop *" type="number" value={form.shop_stock} onChange={v=>set("shop_stock",v)} placeholder="0"/><Field label="Stock in store *" type="number" value={form.store_stock} onChange={v=>set("store_stock",v)} placeholder="0"/><Field label="Notes" value={form.notes} onChange={v=>set("notes",v)} placeholder="Supplier / pack size" wide/><button className="button-main sm:col-span-2">{editing ? "Update stock" : "Save stock item"}</button></div>{notice && <p className="mt-3 font-body text-xs font-bold text-mustard">{notice}</p>}</form><aside className="rounded-2xl border border-mustard/20 bg-mustard/5 p-5"><h2 className="font-display text-xl text-mustard">How alerts work</h2><p className="mt-4 font-body text-sm leading-6 text-[#f5f4fb]/65">Har item ke liye <b className="text-[#f5f4fb]">Low-stock alert at</b> set karein. “1 packet” likhne par shop mein 1 ya us se kam packet hote hi alert show hoga. Store mein stock ho to transfer button se shop refill karein.</p></aside></section>
    <section className="mt-8"><div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><Metric label="Active stock items" value={String(items.length)} tone="text-[#f5f4fb]"/><Metric label="Shop quantity" value={count(shopTotal)} tone="text-leaf"/><Metric label="Store quantity" value={count(storeTotal)} tone="text-mustard"/><Metric label="Need attention" value={String(alerts.length)} tone={alerts.length ? "text-chili" : "text-leaf"}/></div></section>
    <section className="mt-8"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="font-display text-xl text-[#f5f4fb]">Current inventory</h2><input className="field !mt-0 !w-64" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search item..."/></div><div className="mt-3 overflow-x-auto rounded-xl border border-[#f5f4fb]/10">{loading ? <p className="p-6 font-body text-sm text-[#f5f4fb]/45">Loading stock...</p> : <table className="w-full min-w-[820px] text-left"><thead><tr className="border-b border-[#f5f4fb]/10 bg-[#14111a]">{["Item","Unit","Shop stock","Store stock","Alert level","Status","Actions"].map(x=><th key={x} className="px-4 py-3 font-body text-[10px] font-extrabold uppercase text-[#f5f4fb]/45">{x}</th>)}</tr></thead><tbody>{visible.length ? visible.map(x => { const low=Number(x.shop_stock)<=Number(x.low_stock_threshold); const empty=Number(x.shop_stock)+Number(x.store_stock)<=Number(x.low_stock_threshold); return <tr key={x.id} className="border-b border-[#f5f4fb]/5"><td className="cell"><b>{x.name}</b>{x.notes && <small className="block opacity-50">{x.notes}</small>}</td><td className="cell">{x.unit}</td><td className={`cell font-display text-lg ${low ? "text-chili" : "text-leaf"}`}>{count(Number(x.shop_stock))}</td><td className="cell font-display text-lg text-mustard">{count(Number(x.store_stock))}</td><td className="cell">{count(Number(x.low_stock_threshold))} {x.unit}</td><td className="cell"><span className={`rounded-full px-2 py-1 text-[10px] font-bold uppercase ${empty ? "bg-chili/20 text-chili" : low ? "bg-mustard/15 text-mustard" : "bg-leaf/15 text-leaf"}`}>{empty ? "Order now" : low ? "Refill shop" : "In stock"}</span></td><td className="cell">{Number(x.store_stock)>0 && <button onClick={()=>void transfer(x)} className="mr-3 font-bold text-leaf">Transfer</button>}<button onClick={()=>edit(x)} className="mr-3 font-bold text-mustard">Edit</button><button onClick={()=>void archive(x)} className="font-bold text-chili">Remove</button></td></tr>}) : <tr><td colSpan={7} className="p-8 text-center font-body text-sm text-[#f5f4fb]/45">No stock items found.</td></tr>}</tbody></table>}</div></section>
  </main></>;
}
function Field({label,value,onChange,placeholder,type="text",wide=false}:{label:string;value:string;onChange:(v:string)=>void;placeholder?:string;type?:string;wide?:boolean}){return <label className={wide?"sm:col-span-2":""}><span className="label">{label}</span><input required={label.includes("*")} min={type==="number"?"0":undefined} step={type==="number"?"0.01":undefined} className="field" type={type} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></label>}
function Metric({label,value,tone}:{label:string;value:string;tone:string}){return <div className="rounded-xl border border-[#f5f4fb]/10 bg-[#14111a] p-4"><p className="font-body text-[10px] font-extrabold uppercase tracking-wider text-[#f5f4fb]/45">{label}</p><p className={`mt-1 font-display text-2xl ${tone}`}>{value}</p></div>}
